# Generated by Django 4.0.5 on 2022-07-25 19:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('name', models.CharField(default='Ürünün İsmi', max_length=150)),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('seo', models.CharField(default='Seo için Bilgi Giriniz.', max_length=500)),
                ('key', models.CharField(default='Keyword için Giriş', max_length=550)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Producy',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Konut', 'Konut'), ('İş Yeri', 'İş Yeri'), ('Arsa', 'Arsa'), ('Turizm', 'Turizm')], default='İlçeyi Giriniz', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.city'),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.region'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.type'),
        ),
    ]
