# Generated by Django 4.0.5 on 2022-07-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_alter_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='garage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='m2',
            field=models.IntegerField(default=0),
        ),
    ]
