# Generated by Django 4.0.5 on 2022-07-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_product_bathrooms_product_bedrooms_product_garage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='room',
            field=models.IntegerField(default=0),
        ),
    ]
