# Generated by Django 4.0.5 on 2022-07-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_product_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=21, max_length=200),
            preserve_default=False,
        ),
    ]
