# Generated by Django 4.0.5 on 2022-07-25 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1+0', '1+0'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1', '4+1'), ('5+1', '5+1'), ('6+1', '6+1'), ('7+1', '7+1'), ('3+2', '3+2'), ('4+2', '4+2'), ('5+2', '5+2')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='model',
            field=models.CharField(db_index=True, default='Modeli Yazınıcız', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.room'),
        ),
    ]
