# Generated by Django 4.0.5 on 2022-07-26 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0009_agent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='agent',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='realestate.agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='opportunity',
            field=models.BooleanField(default=False),
        ),
    ]
