# Generated by Django 4.0.5 on 2022-07-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0010_product_agent_product_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pool',
            field=models.BooleanField(default=False),
        ),
    ]
