# Generated by Django 4.0.5 on 2022-07-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0012_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='house3d',
            field=models.BooleanField(default=False),
        ),
    ]
