# Generated by Django 4.0.5 on 2022-08-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0016_alter_product_garage'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d'),
        ),
    ]
