# Generated by Django 4.0.5 on 2022-08-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0017_agent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='about',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d'),
        ),
    ]
