# Generated by Django 4.0.5 on 2022-08-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0019_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.SlugField(default=21, max_length=200),
            preserve_default=False,
        ),
    ]
