# Generated by Django 4.0.5 on 2022-08-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0020_type_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='build',
            field=models.CharField(default='Yapılış Yılı', max_length=150),
        ),
    ]
