# Generated by Django 4.0.5 on 2022-08-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0021_product_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='floor',
            field=models.CharField(default='Kat', max_length=150),
        ),
    ]
