# Generated by Django 4.0.5 on 2022-08-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0022_product_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='adress',
            field=models.CharField(default='Evin Tam Adresi', max_length=150),
        ),
    ]
