# Generated by Django 4.0.5 on 2022-08-13 11:19

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0023_product_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=places.fields.PlacesField(default=21, max_length=255),
            preserve_default=False,
        ),
    ]
