# Generated by Django 4.0.5 on 2022-08-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0024_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Konut', 'Konut'), ('İş Yeri', 'İş Yeri'), ('Arsa', 'Arsa'), ('Turizm', 'Turizm'), ('Bina', 'Bina')], max_length=10),
        ),
    ]
