# Generated by Django 4.0.5 on 2022-08-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0026_muhit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Muhit',
        ),
    ]
