# Generated by Django 4.0.5 on 2022-08-15 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0027_delete_muhit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muhit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sea', models.BooleanField(default=False, verbose_name='Denize Sıfır')),
                ('hospital', models.BooleanField(default=False, verbose_name='Hastane')),
                ('citycenter', models.BooleanField(default=False, verbose_name='Şehir Merkezi')),
                ('municipality', models.BooleanField(default=False, verbose_name='Belediye')),
                ('pharmacy', models.BooleanField(default=False, verbose_name='Eczane')),
                ('market', models.BooleanField(default=False, verbose_name='Eczane')),
                ('park', models.BooleanField(default=False, verbose_name='Park')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.product')),
            ],
        ),
    ]
