# Generated by Django 4.0.5 on 2022-08-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0029_rename_muhit_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='citycenter',
            field=models.BooleanField(default=False, verbose_name='Şehir Merkezi'),
        ),
        migrations.AddField(
            model_name='product',
            name='hospital',
            field=models.BooleanField(default=False, verbose_name='Hastane'),
        ),
        migrations.AddField(
            model_name='product',
            name='market',
            field=models.BooleanField(default=False, verbose_name='Eczane'),
        ),
        migrations.AddField(
            model_name='product',
            name='municipality',
            field=models.BooleanField(default=False, verbose_name='Belediye'),
        ),
        migrations.AddField(
            model_name='product',
            name='park',
            field=models.BooleanField(default=False, verbose_name='Park'),
        ),
        migrations.AddField(
            model_name='product',
            name='pharmacy',
            field=models.BooleanField(default=False, verbose_name='Eczane'),
        ),
        migrations.AddField(
            model_name='product',
            name='sea',
            field=models.BooleanField(default=False, verbose_name='Denize Sıfır'),
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
