# Generated by Django 4.0.5 on 2022-08-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0030_product_citycenter_product_hospital_product_market_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='market',
            field=models.BooleanField(default=False, verbose_name='Market'),
        ),
    ]
