# Generated by Django 4.0.5 on 2022-08-16 13:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0032_product_fitness_product_mosque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
    ]
