# Generated by Django 4.0.5 on 2022-08-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0033_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Works',
        ),
    ]
