# Generated by Django 4.0.5 on 2022-08-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0034_rename_gallery_works'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='info',
        ),
    ]
